/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tuxido;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JDesktopPane;

/**
 *
 * @author vj002349
 */
public class ifrmTablaSeg extends javax.swing.JInternalFrame {

    hiloTablaSeg hilo;
    private String query;
    private String fecha;
    int fila;
    private final JDesktopPane Pane3;
    /**
     * Creates new form ifrmTablaSeg
     * @param jDesktopPane3 
     */
    public ifrmTablaSeg(JDesktopPane jDesktopPane3) {
        initComponents();
        Pane3=jDesktopPane3;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        real = new javax.swing.JRadioButton();
        ord = new javax.swing.JRadioButton();
        orden = new javax.swing.JTextField();
        DETENER = new javax.swing.JButton();
        INICIAR = new javax.swing.JButton();
        CERRAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        jMenuItem1.setText("Ver Info.");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setMaximizable(true);
        setResizable(true);
        setTitle("Tuxedo | Tabla de Seguimiento");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seguimiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 10))); // NOI18N

        buttonGroup1.add(real);
        real.setSelected(true);
        real.setText("Tiempo Real");

        buttonGroup1.add(ord);
        ord.setText("Orden Produccion");

        orden.setBackground(new java.awt.Color(204, 204, 255));
        orden.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        DETENER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/stop_blue.png"))); // NOI18N
        DETENER.setText("Detener");
        DETENER.setEnabled(false);
        DETENER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DETENERActionPerformed(evt);
            }
        });

        INICIAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/play_blue.png"))); // NOI18N
        INICIAR.setText("Iniciar");
        INICIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INICIARActionPerformed(evt);
            }
        });

        CERRAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        CERRAR.setText("Cerrar");
        CERRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CERRARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(real)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orden, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INICIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DETENER)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CERRAR)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(real)
                    .addComponent(ord)
                    .addComponent(orden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DETENER)
                    .addComponent(INICIAR)
                    .addComponent(CERRAR))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "VIN", "Descripcion", "Color", "Año Modelo", "Soldadura", "Liberada", "Pintura", "Liberada", "Ensamble", "Liberada", "Calidad", "Liberada", "Empaque", "Liberada", "Embarque", "Liberada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabla.setComponentPopupMenu(jPopupMenu1);
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        tabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);
        tabla.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabla.getColumnModel().getColumn(1).setPreferredWidth(120);
        tabla.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabla.getColumnModel().getColumn(3).setPreferredWidth(100);
        tabla.getColumnModel().getColumn(4).setPreferredWidth(100);
        tabla.getColumnModel().getColumn(5).setPreferredWidth(80);
        tabla.getColumnModel().getColumn(7).setPreferredWidth(80);
        tabla.getColumnModel().getColumn(9).setPreferredWidth(80);
        tabla.getColumnModel().getColumn(11).setPreferredWidth(80);
        tabla.getColumnModel().getColumn(13).setPreferredWidth(80);
        tabla.getColumnModel().getColumn(15).setPreferredWidth(80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INICIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INICIARActionPerformed
        // TODO add your handling code here:
                Date fechaActual=new Date();
                SimpleDateFormat forFecha=new SimpleDateFormat("MM-dd-yyyy");
                fecha=forFecha.format(fechaActual);
        if(real.isSelected()==true){
            query="select ID, VIN, MOD_DESC, COL_DESC, ANIO, "
                    + "WE_STATUS, TO_CHAR(WE_TIM,'DD/MM/YYYY HH:MI:SS AM'), "
                    + "PA_STATUS, TO_CHAR(PA_TIM,'DD/MM/YYYY HH:MI:SS AM'), "
                    + "AF_STATUS, TO_CHAR(AF_TIM,'DD/MM/YYYY HH:MI:SS AM'), "
                    + "VQ_STATUS, TO_CHAR(VQ_TIM,'DD/MM/YYYY HH:MI:SS AM'), "
                    + "PK_STATUS, TO_CHAR(PK_TIM,'DD/MM/YYYY HH:MI:SS AM'), "
                    + "SHP_STATUS, TO_CHAR(SHP_TIM,'DD/MM/YYYY HH:MI:SS AM') "
                    + "from TX_ORDEN_PROD WHERE SHP_STATUS='Pendiente' order by ID ASC";
        }else{
            query="select ID, VIN, MOD_DESC, COL_DESC, ANIO, "
                    + "WE_STATUS, TO_CHAR(WE_TIM,'DD/MM/YYYY HH:MI:SS AM'), "
                    + "PA_STATUS, TO_CHAR(PA_TIM,'DD/MM/YYYY HH:MI:SS AM'), "
                    + "AF_STATUS, TO_CHAR(AF_TIM,'DD/MM/YYYY HH:MI:SS AM'), "
                    + "VQ_STATUS, TO_CHAR(VQ_TIM,'DD/MM/YYYY HH:MI:SS AM'), "
                    + "PK_STATUS, TO_CHAR(PK_TIM,'DD/MM/YYYY HH:MI:SS AM'), "
                    + "SHP_STATUS, TO_CHAR(SHP_TIM,'dd/MM/yyy HH:mm:ss') "
                    + " from TX_ORDEN_PROD WHERE ID_ORDEN='"+orden.getText()+"' order by ID ASC";
        }
        hilo=new hiloTablaSeg(tabla,query);
        INICIAR.setEnabled(false);
        DETENER.setEnabled(true);
        hilo.start();
    }//GEN-LAST:event_INICIARActionPerformed

    private void DETENERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DETENERActionPerformed
        // TODO add your handling code here:
        DETENER.setEnabled(false);
        INICIAR.setEnabled(true);
        hilo.deterHilo();
    }//GEN-LAST:event_DETENERActionPerformed

    private void CERRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CERRARActionPerformed
        // TODO add your handling code here:
        hilo.deterHilo();
        dispose();
    }//GEN-LAST:event_CERRARActionPerformed

    private void tablaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyReleased
        // TODO add your handling code here:
        fila = tabla.getSelectedRow();
    }//GEN-LAST:event_tablaKeyReleased

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        fila=tabla.getSelectedRow();
    }//GEN-LAST:event_tablaMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        String VIN=tabla.getValueAt(fila, 1).toString();
        ifrmInfoUnidad ifrmiu=new ifrmInfoUnidad(Pane3, VIN);
        Pane3.add(ifrmiu);
        ifrmiu.setLocation(20, 90);
        ifrmiu.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CERRAR;
    private javax.swing.JButton DETENER;
    private javax.swing.JButton INICIAR;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton ord;
    private javax.swing.JTextField orden;
    private javax.swing.JRadioButton real;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}