/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tuxido.WP;

import java.awt.Dimension;
import javax.swing.JDesktopPane;

/**
 *
 * @author VJ002349
 */
public class ifrmWPReportes extends javax.swing.JInternalFrame {
    JDesktopPane Panel5;
    /**
     * Creates new form ifrmWPReportes
     */
    public ifrmWPReportes(JDesktopPane jDesktopPane) {
        Panel5 = jDesktopPane;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar4 = new javax.swing.JToolBar();
        btnSeg = new javax.swing.JButton();
        btnINC = new javax.swing.JButton();
        btnCT = new javax.swing.JButton();
        btnSHP1 = new javax.swing.JButton();
        btnRPRD = new javax.swing.JButton();

        setTitle("Tuxedo - WaterPump |  Reportes");

        jToolBar4.setFloatable(false);

        btnSeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/map_start.png"))); // NOI18N
        btnSeg.setToolTipText("Seguimiento Linea Produccion");
        btnSeg.setFocusable(false);
        btnSeg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSeg.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSegActionPerformed(evt);
            }
        });
        jToolBar4.add(btnSeg);

        btnINC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book_addresses_error.png"))); // NOI18N
        btnINC.setToolTipText("Incidencias");
        btnINC.setFocusable(false);
        btnINC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnINC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnINC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnINCActionPerformed(evt);
            }
        });
        jToolBar4.add(btnINC);

        btnCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_alert.png"))); // NOI18N
        btnCT.setToolTipText("Cortes de Turnos");
        btnCT.setFocusable(false);
        btnCT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTActionPerformed(evt);
            }
        });
        jToolBar4.add(btnCT);

        btnSHP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lorry_start.png"))); // NOI18N
        btnSHP1.setToolTipText("Info. Embarque");
        btnSHP1.setFocusable(false);
        btnSHP1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSHP1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSHP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSHP1ActionPerformed(evt);
            }
        });
        jToolBar4.add(btnSHP1);

        btnRPRD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/layout_lightning.png"))); // NOI18N
        btnRPRD.setToolTipText("Reportes de Produccion");
        btnRPRD.setFocusable(false);
        btnRPRD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRPRD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRPRD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRPRDActionPerformed(evt);
            }
        });
        jToolBar4.add(btnRPRD);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar4, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar4, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSegActionPerformed
        // TODO add your handling code here:
        /*ifrmSegPlan ifrmspl=new ifrmSegPlan(Panel5);
        Dimension desktopSize = Panel5.getSize();
        Dimension jInternalFrameSize = ifrmspl.getSize();
        Panel5.add(ifrmspl);
        ifrmspl.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
        ifrmspl.show();*/
    }//GEN-LAST:event_btnSegActionPerformed

    private void btnINCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnINCActionPerformed
        // TODO add your handling code here:
        /*ifrmRepIncidentes ifrmrin=new ifrmRepIncidentes(Panel5);
        Dimension desktopSize = Panel5.getSize();
        Dimension jInternalFrameSize = ifrmrin.getSize();
        Panel5.add(ifrmrin);
        ifrmrin.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
        ifrmrin.show();*/
    }//GEN-LAST:event_btnINCActionPerformed

    private void btnCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTActionPerformed
        // TODO add your handling code here:
        ifrmWPRepCorte ifrmrc=new ifrmWPRepCorte(Panel5);
        Dimension desktopSize = Panel5.getSize();
        Dimension jInternalFrameSize = ifrmrc.getSize();
        Panel5.add(ifrmrc);
        ifrmrc.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
        ifrmrc.show();
    }//GEN-LAST:event_btnCTActionPerformed

    private void btnSHP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSHP1ActionPerformed
        // TODO add your handling code here:
        ifrmWPCtrlBtc ifrmcbt=new ifrmWPCtrlBtc(Panel5);
        Dimension desktopSize = Panel5.getSize();
        Dimension jInternalFrameSize = ifrmcbt.getSize();
        Panel5.add(ifrmcbt);
        ifrmcbt.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
        ifrmcbt.show();
    }//GEN-LAST:event_btnSHP1ActionPerformed

    private void btnRPRDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRPRDActionPerformed
        // TODO add your handling code here:
        ifrmWPRepProduccion ifrmrp=new ifrmWPRepProduccion(Panel5);
        Dimension desktopSize = Panel5.getSize();
        Dimension jInternalFrameSize = ifrmrp.getSize();
        Panel5.add(ifrmrp);
        ifrmrp.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
        ifrmrp.show();
    }//GEN-LAST:event_btnRPRDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCT;
    private javax.swing.JButton btnINC;
    private javax.swing.JButton btnRPRD;
    private javax.swing.JButton btnSHP1;
    private javax.swing.JButton btnSeg;
    private javax.swing.JToolBar jToolBar4;
    // End of variables declaration//GEN-END:variables
}
